name: Make Unique

on: [push, pull_request]

jobs:
  ut:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: mkdir module1/homework/make_unique/build
      run: mkdir module1/homework/make_unique/build
    - name: Compile
      working-directory: module1/homework/make_unique/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: module1/homework/make_unique/build
      run: ctest -V

  ut_valgrind:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: mkdir module1/homework/make_unique/build
      run: mkdir module1/homework/make_unique/build
    - name: Compile
      working-directory: module1/homework/make_unique/build
      run: |
        cmake ..
        make
    - name: Run UTs with valgrind
      working-directory: module1/homework/make_unique/build
      run: valgrind --leak-check=full ./MakeUnique-ut
